services:
  nginx:
    image: nginx:latest
    container_name: pihole_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:z
    ports:
      - "81:80" # nginx is not supposed to use port 80. Change this to your own port
    environment:
      - LANG=en_EN.UTF-8
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    depends_on:
      - pihole
    networks:
      - pihole_net

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # port 80 not exposed since it will passed into nginx
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./conf/pihole/pihole.log:/var/log/pihole.log
      - ./conf/pihole/pihole/:/etc/pihole/
      - ./conf/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      ServerIP: 127.0.0.1 # set your own host IP
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      VIRTUAL_PORT: 80
      LANG: 'en_EN.UTF-8'
      TZ: 'Asia/Kuala_Lumpur'
      WEBPASSWORD: 'YourOwnPassword'
    restart: unless-stopped
    networks:
      - pihole_net

networks:
  pihole_net:
