services:
  nginx:
    image: nginx:latest
    container_name: pihole_nginx
    volumes:
      # - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - '/var/run/docker.sock:/tmp/docker.sock'
    ports:
      #- "81:80" # nginx is not supposed to use port 80. Change this to your own port
      - "80:80"
    environment:
      - DEFAULT_HOST=pihole.home.net
      - LANG=en_EN.UTF-8
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    depends_on:
      - pihole
    # networks:
    #   - pihole_net

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # port 80 not exposed since it will passed into nginx
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - '8080:80/tcp'
    volumes:
      - ./conf/pihole/pihole.log:/var/log/pihole.log
      - ./conf/pihole/pihole/:/etc/pihole/
      - ./conf/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    environment:
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      FTLCONF_LOCAL_IPV4: 192.168.0.14
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.home.net
      VIRTUAL_PORT: 80
      LANG: 'en_EN.UTF-8'
      TZ: 'Asia/Kuala_Lumpur'
      WEBPASSWORD: 'YourOwnPassword' # change this
    restart: unless-stopped
#     networks:
#       - pihole_net

# networks:
#   pihole_net:
